from __future__ import annotations

GRAY_18 = '#767676'
GRAY_0 = '#000000'
GRAY_1 = '#101010'
GRAY_2 = '#1a1a1a'
GRAY_3 = '#262626'
GRAY_4 = '#404040'

ACCENT_COLOR_TEXT = "#ee9470"
TEXT_DIM = '#8d8d8d'
TEXT_MAIN = "#cecece"
TEXT_HI = '#f2f2f2'

FONT_WEIGHT_SEMIBOLD = 600
FONT_WEIGHT_BOLD = 700

# Layout rhythm
SIZE_TAB_STRIP_OFFSET = '0px'
SIZE_TAB_MARGIN_RIGHT = '4px'
SIZE_FORM_SPACING = '4px'
SIZE_CHECKBOX_SPACING = '6px'
SIZE_SPLITTER_HANDLE_WIDTH = '1px'
SIZE_SPLITTER_HANDLE_MARGIN_LEFT = '8px'
SIZE_SECTION_STACK_SPACING = '6px'

# Inline paddings
SIZE_CONTROL_PADDING = '2px 4px'
SIZE_BUTTON_PADDING = '0px 6px'
SIZE_HEADER_PADDING = '2px 6px'
SIZE_TAB_PADDING = '4px 8px'
SIZE_TOOLBUTTON_PADDING = '2px 4px'
SIZE_TOOLBUTTON_POPUP_PADDING_RIGHT = '2px'

# Heights and widths
SIZE_CONTROL_MIN_HEIGHT = '18px'
SIZE_COMPACT_BUTTON_MIN_HEIGHT = '20px'
SIZE_BUTTON_MIN_HEIGHT = '30px'
SIZE_FOOTER_MIN_HEIGHT = SIZE_BUTTON_MIN_HEIGHT
SIZE_SPIN_BUTTON_WIDTH = '12px'
SIZE_COMBO_DROPDOWN_WIDTH = '14px'
SIZE_CHECKBOX_INDICATOR = '14px'
SIZE_SCROLLBAR_HANDLE_MIN = '24px'

# Runtime layout metrics
SIZE_APP_MARGIN = 6
SIZE_PANEL_MARGIN = 10
SIZE_TAB_CONTENT_TOP_MARGIN = 20
SIZE_SECTION_FRAME_MARGIN = 8
SIZE_SECTION_FRAME_INDENT = 24
SIZE_FOOTER_ITEM_SPACING = 4
SIZE_FOOTER_TOP_SPACING = 8
SIZE_FOOTER_BOTTOM_INSET = 6

# Widget color definitions
BASE_BG = GRAY_0
PANEL_BG = GRAY_0
PANEL_BG_ACTIVE = GRAY_1
TAB_SELECTED_BG = GRAY_0
TAB_TEXT_ACCENT = ACCENT_COLOR_TEXT
CONTROL_BG = GRAY_1
CONTROL_BG_HOVER = GRAY_2
CONTROL_BG_PRESSED = GRAY_1
CONTROL_MENU_BG = GRAY_0
CONTROL_SELECTION_BG = GRAY_2
TEXT_SELECTION_BG = GRAY_4
HEADER_BG = GRAY_1
CHECKED_BG = GRAY_2
DISABLED_BG = GRAY_1
SCROLLBAR_HANDLE_BG = GRAY_2
SPLITTER_BG = GRAY_1
STATUS_BG = GRAY_2
BUTTON_ACCENT_BG = GRAY_1
BUTTON_ACCENT_BG_HOVER = GRAY_2
BUTTON_ACCENT_BG_PRESSED = GRAY_1
TEXT_PRIMARY = TEXT_MAIN
TEXT_SOFT = TEXT_DIM
TEXT_BRIGHT = TEXT_HI
TEXT_HEADER = TEXT_MAIN
TEXT_CONTROL = TEXT_MAIN
TEXT_HEADER_SECTION = TEXT_DIM
TEXT_ACCENT = ACCENT_COLOR_TEXT
TEXT_STATUS = TEXT_MAIN
HEADER_DIVIDER_LINE = GRAY_1
BOOL_EDITOR_HOVER_BG = GRAY_2
BOOL_EDITOR_FILL_ENABLED = GRAY_1
BOOL_EDITOR_FILL_DISABLED = GRAY_1
BOOL_EDITOR_CHECKED_ENABLED = GRAY_1
BOOL_EDITOR_CHECKED_DISABLED = GRAY_1
BOOL_EDITOR_BORDER_CHECKED = GRAY_0
BOOL_EDITOR_BORDER_UNCHECKED = GRAY_0
BOOL_EDITOR_CHECKMARK = TEXT_MAIN