from __future__ import annotations

GRAY_0 = '#767676'
GRAY_1 = '#808080'
GRAY_2 = '#8a8a8a'
GRAY_3 = '#909090'
TEXT_DIM = '#ececec'
TEXT_MAIN = '#ffffff'
TEXT_BOLD = '#ffffff'

FONT_SIZE_BASE = '12pt'
FONT_SIZE_TAB = '8pt'

FONT_WEIGHT_SEMIBOLD = 600
FONT_WEIGHT_BOLD = 700

# Layout rhythm
SIZE_TAB_STRIP_OFFSET = '0px'
SIZE_TAB_MARGIN_RIGHT = '4px'
SIZE_FORM_SPACING = '4px'
SIZE_CHECKBOX_SPACING = '6px'
SIZE_SPLITTER_HANDLE_WIDTH = '4px'
SIZE_SECTION_STACK_SPACING = '6px'

# Inline paddings
SIZE_CONTROL_PADDING = '2px 4px'
SIZE_BUTTON_PADDING = '0px 6px'
SIZE_HEADER_PADDING = '2px 6px'
SIZE_TAB_PADDING = '4px 8px'
SIZE_TOOLBUTTON_PADDING = '2px 4px'
SIZE_TOOLBUTTON_POPUP_PADDING_RIGHT = '2px'

# Heights and widths
SIZE_CONTROL_MIN_HEIGHT = '18px'
SIZE_BUTTON_MIN_HEIGHT = '30px'
SIZE_FOOTER_MIN_HEIGHT = SIZE_BUTTON_MIN_HEIGHT
SIZE_SPIN_BUTTON_WIDTH = '12px'
SIZE_COMBO_DROPDOWN_WIDTH = '14px'
SIZE_CHECKBOX_INDICATOR = '14px'
SIZE_SCROLLBAR_HANDLE_MIN = '24px'

# Runtime layout metrics
SIZE_APP_MARGIN = 6
SIZE_PANEL_MARGIN = 10
SIZE_TAB_CONTENT_TOP_MARGIN = 16
SIZE_SECTION_FRAME_MARGIN = 8
SIZE_SECTION_FRAME_INDENT = 24
SIZE_FOOTER_ITEM_SPACING = 4
SIZE_FOOTER_BOTTOM_INSET = 6

BASE_BG = GRAY_0
PANEL_BG = GRAY_0
PANEL_BG_ACTIVE = GRAY_1
TAB_SELECTED_BG = GRAY_2
CONTROL_BG = GRAY_2
CONTROL_BG_HOVER = GRAY_2
CONTROL_BG_PRESSED = GRAY_1
CONTROL_MENU_BG = GRAY_2
CONTROL_SELECTION_BG = GRAY_3
HEADER_BG = GRAY_1
CHECKED_BG = GRAY_3
DISABLED_BG = GRAY_1
SCROLLBAR_HANDLE_BG = GRAY_3
SPLITTER_BG = GRAY_1
STATUS_BG = GRAY_2
TEXT_PRIMARY = TEXT_MAIN
TEXT_SOFT = TEXT_DIM
TEXT_BRIGHT = TEXT_BOLD
TEXT_HEADER = TEXT_MAIN
TEXT_CONTROL = TEXT_MAIN
TEXT_HEADER_SECTION = TEXT_DIM
TEXT_STATUS = TEXT_MAIN
DIVIDER_SUBTLE = GRAY_1